class_name CathedralSomaticEngine
extends RefCounted

enum ParamIdx {
	CRANIAL_VAULT_DEPTH,
	CLEARANCE_CRANIAL_CALVARIA_OFFSET,
	OSTEOLOGY_BICRISTAL_PELVIC_WIDTH,
	ADIPOSE_VISCERAL,
	ADIPOSE_FEMORAL_ANTERIOR,
	HYPERTROPHY_PECTORALIS_MAJOR,
	HYPERTROPHY_RECTUS_FEMORIS,
	VASCULARITY_FOREARM_ANTERIOR,
	DERMAL_ERYTHEMA_BASAL,
	DERMAL_MELANIN_CONCENTRATION,
	RESONANCE_AFIELD_CONDUCTANCE,
	RESONANCE_OCULAR_CYAN_LUMINOSITY
}

static func evaluate_somatic_resonance(hp: float, buffer: float) -> float:
    return clamp((hp + buffer) / 200.0, 0.0, 1.0)
